# Generated by Django 6.0.3 on 2026-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy_stock', 'Buy Stock'), ('sell_stock', 'Sell Stock'), ('buy_vehicle_share', 'Buy Vehicle Share'), ('buy_vehicle', 'Buy Full Vehicle'), ('vehicle_share_dividend', 'Vehicle Share Dividend'), ('vehicle_share_sale', 'Vehicle Share Sale')], max_length=30),
        ),
    ]
