# Generated by Django 6.0.3 on 2026-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('usdt', 'USDT'), ('btc', 'BTC'), ('usdc', 'USDC'), ('ethereum', 'Ethereum')], default='btc', max_length=20),
        ),
    ]
