# Generated by Django 6.0.3 on 2026-03-23 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(choices=[('model_3', 'Model 3'), ('model_y', 'Model Y'), ('model_s', 'Model S'), ('model_x', 'Model X'), ('cybertruck', 'Cybertruck'), ('roadster', 'Roadster')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-Owned')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Full vehicle price', max_digits=12)),
                ('share_price', models.DecimalField(decimal_places=2, help_text='Price per share', max_digits=10)),
                ('total_shares', models.PositiveIntegerField(default=100)),
                ('available_shares', models.PositiveIntegerField(default=100)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Mileage for used vehicles', null=True)),
                ('color', models.CharField(default='White', max_length=50)),
                ('interior_color', models.CharField(blank=True, max_length=50)),
                ('battery_range', models.PositiveIntegerField(help_text='Range in miles')),
                ('acceleration', models.DecimalField(decimal_places=1, help_text='0-60 mph in seconds', max_digits=4)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('autopilot', models.BooleanField(default=True)),
                ('premium_audio', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_purchases', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSharePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_purchased', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_reference', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_shares', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchases', to='vehicles.vehicle')),
            ],
        ),
    ]
